### PR TITLE
[fix] workspace per monitor option

### LINKED ISSUE #560: Using HyprPanel with hyprsplit does not work well
**Describe the bug**
I use https://github.com/shezdy/hyprsplit to have separate workspaces per monitor similarly to awesome.

Using waybar they have an implementation that shows things correctly on each bar but in hyprpanel this very clearly does not work.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by edjubert**
When activating the option *Mask Workspace Numbers On Monitors*, it should show only workspace attached to the monitor.

## Description
In the function `getWorkspaceRules`, there is a call to the `workspacerules` dispatcher that returns (in my case) an object formatted like:
```json
[{
  "workspaceString": "eDP-1"
},
{
  "workspaceString": "HDMI-1"
}]
```
The `WorkspaceRule` looks like this:
```ts
type WorkspaceRule {
  "workspaceString": string,
  "monitor": string
}
```

The function expects `workspaceString` to be an `int` but, as we saw, the output is the monitor name and not the monitor ID. Maybe `hyprctl` updates the dispatcher or `hyprsplit` modifies it.

To fix this, I relied on `hyprctl workspaces -j` command instead of `workspacerules`.

## Additional change
I also renamed the option *Mask Workspace Numbers On Monitors* to *Workspace per monitor*.

## Closing
close #560

### CODE REVIEW

**Comment by davfsa** [comment]
Note, this will also close https://github.com/Jas-SinghFSU/HyprPanel/issues/488

**Comment by Jas-SinghFSU** [comment]
A few issues I've noticed:
1. The `Total Workspaces` property which shows a minimum number of workspaces at all times, no longer works
2. A new workspace shows up on all monitors until you restart with that workspace active

**Comment by davfsa** [comment]
> The Total Workspaces property which shows a minimum number of workspaces at all times, no longer works

I believe it is intended for it not to work with "Workspace per monitor"

https://github.com/Jas-SinghFSU/HyprPanel/blob/99b173bc581e7a4409b3931726cf8e775c7264b9/src/components/bar/modules/workspaces/helpers/index.ts#L316-L324

Note the lack of `allWorkspaces` if binding to monitor specific. It also looks weird if you try to add it, as hyprpanel assumes that workspaces will be sequencial per monitor, which is not necessarily the case (ie, hyprsplit)

> A new workspace shows up on all monitors until you restart with that workspace active

Nice spot! The attached patch should fix it, as they are no longer "rules" and are just a mapping (they were never really rules anyways)

cc @edjubert 

<details>

<summary>Patch</summary>

```diff
diff --git a/src/components/bar/modules/workspaces/helpers/index.ts b/src/components/bar/modules/workspaces/helpers/index.ts
index 5616db7..aec7b65 100644
--- a/src/components/bar/modules/workspaces/helpers/index.ts
+++ b/src/components/bar/modules/workspaces/helpers/index.ts
@@ -56,25 +56,25 @@ export const getWorkspacesForMonitor = (
 
 /**
- * Retrieves the workspace rules.
+ * Retrieves the workspace client mapping.
  *
- * This function fetches and parses the workspace rules from the Hyprland service.
+ * This function fetches and parses the workspaces mapping from the Hyprland service.
  *
- * @returns The workspace rules map.
+ * @returns The workspace client map.
  */
-export const getWorkspaceRules = (): WorkspaceMap => {
+export const getWorkspaceMapping = (): WorkspaceMap => {
     try {
         const rules = exec('hyprctl workspaces -j');
 
-        const workspaceRules: WorkspaceMap = {};
+        const workspaceMap: WorkspaceMap = {};
 
         JSON.parse(rules).forEach((rule: HyprctlWorkspace) => {
-            if (Object.hasOwnProperty.call(workspaceRules, rule.monitor)) {
-                workspaceRules[rule.monitor].push(rule.id);
+            if (Object.hasOwnProperty.call(workspaceMap, rule.monitor)) {
+                workspaceMap[rule.monitor].push(rule.id);
             } else {
-                workspaceRules[rule.monitor] = [rule.id];
+                workspaceMap[rule.monitor] = [rule.id];
             }
         });
 
-        return workspaceRules;
+        return workspaceMap;
     } catch (err) {
         console.error(err);
@@ -97,5 +97,5 @@ export const getCurrentMonitorWorkspaces = (monitor: number): number[] => {
     }
 
-    const monitorWorkspaces = getWorkspaceRules();
+    const monitorWorkspaces = getWorkspaceMapping();
     const monitorMap: MonitorMap = {};
     hyprlandService.get_monitors().forEach((m) => (monitorMap[m.id] = m.name));
@@ -266,5 +266,5 @@ export const createThrottledScrollHandlers = (
  * @param totalWorkspaces - The total number of workspaces.
  * @param workspaceList - The list of workspaces.
- * @param workspaceRules - The workspace rules map.
+ * @param workspaceMapping - The workspace mapping.
  * @param monitor - The monitor ID.
  * @param isMonitorSpecific - Whether the workspaces are monitor-specific.
@@ -276,5 +276,5 @@ export const getWorkspacesToRender = (
     totalWorkspaces: number,
     workspaceList: AstalHyprland.Workspace[],
-    workspaceRules: WorkspaceMap,
+    workspaceMapping: WorkspaceMap,
     monitor: number,
     isMonitorSpecific: boolean,
@@ -295,6 +295,6 @@ export const getWorkspacesToRender = (
         monitorList.find((mon) => mon.id === monitor) || workspaceMonitorList.find((mon) => mon.id === monitor);
 
-    const workspacesWithRules = Object.keys(workspaceRules).reduce((acc: number[], k: string) => {
-        return [...acc, ...workspaceRules[k]];
+    const workspacesWithRules = Object.keys(workspaceMapping).reduce((acc: number[], k: string) => {
+        return [...acc, ...workspaceMapping[k]];
     }, []);
 
@@ -302,8 +302,8 @@ export const getWorkspacesToRender = (
         if (
             curMonitor &&
-            Object.hasOwnProperty.call(workspaceRules, curMonitor.name) &&
+            Object.hasOwnProperty.call(workspaceMapping, curMonitor.name) &&
             workspacesWithRules.includes(w)
         ) {
-            return workspaceRules[curMonitor.name].includes(w);
+            return workspaceMapping[curMonitor.name].includes(w);
         }
         return true;
@@ -312,5 +312,5 @@ export const getWorkspacesToRender = (
     if (isMonitorSpecific) {
         const workspacesInRange = range(totalWorkspaces).filter((ws) => {
-            return getWorkspacesForMonitor(ws, workspaceRules, monitor, wsList, monitorList);
+            return getWorkspacesForMonitor(ws, workspaceMapping, monitor, wsList, monitorList);
         });
 
@@ -324,8 +324,8 @@ export const getWorkspacesToRender = (
 
 /**
- * The workspace rules variable.
- * This variable holds the current workspace rules.
+ * The workspace mapping variable.
+ * This variable holds the current workspace mapping.
  */
-export const workspaceRules = Variable(getWorkspaceRules());
+export const workspaceMapping = Variable(getWorkspaceMapping());
 
 /**
@@ -341,5 +341,21 @@ export const forceUpdater = Variable(true);
 export const setupConnections = (): void => {
     hyprlandService.connect('config-reloaded', () => {
-        workspaceRules.set(getWorkspaceRules());
+        workspaceMapping.set(getWorkspaceMapping());
+    });
+
+    hyprlandService.connect('workspace-added', () => {
+        workspaceMapping.set(getWorkspaceMapping());
+    });
+
+    hyprlandService.connect('workspace-removed', () => {
+        workspaceMapping.set(getWorkspaceMapping());
+    });
+
+    hyprlandService.connect('monitor-added', () => {
+        workspaceMapping.set(getWorkspaceMapping());
+    });
+
+    hyprlandService.connect('monitor-removed', () => {
+        workspaceMapping.set(getWorkspaceMapping());
     });
 
diff --git a/src/components/bar/modules/workspaces/workspaces.tsx b/src/components/bar/modules/workspaces/workspaces.tsx
index 65122d4..d70a22e 100644
--- a/src/components/bar/modules/workspaces/workspaces.tsx
+++ b/src/components/bar/modules/workspaces/workspaces.tsx
@@ -1,5 +1,5 @@
 import { hyprlandService } from 'src/lib/constants/services';
 import options from 'src/options';
-import { forceUpdater, getWorkspacesToRender, isWorkspaceIgnored, setupConnections, workspaceRules } from './helpers';
+import { forceUpdater, getWorkspacesToRender, isWorkspaceIgnored, setupConnections, workspaceMapping } from './helpers';
 import { getAppIcon, getWsColor, renderClassnames, renderLabel } from './helpers/utils';
 import { ApplicationIcons, WorkspaceIconMap } from 'src/lib/types/workspace';
@@ -61,5 +61,5 @@ export const WorkspaceModule = ({ monitor }: WorkspaceModuleProps): JSX.Element
             bind(showAllActive),
             bind(hyprlandService, 'focusedWorkspace'),
-            bind(workspaceRules),
+            bind(workspaceMapping),
             bind(forceUpdater),
         ],
@@ -92,5 +92,5 @@ export const WorkspaceModule = ({ monitor }: WorkspaceModuleProps): JSX.Element
                 totalWorkspaces,
                 workspaceList,
-                workspaceRules.get(),
+                workspaceMapping.get(),
                 monitor,
                 isMonitorSpecific,
diff --git a/src/lib/types/workspace.d.ts b/src/lib/types/workspace.d.ts
index 885c09c..ff2165b 100644
--- a/src/lib/types/workspace.d.ts
+++ b/src/lib/types/workspace.d.ts
@@ -1,16 +1,5 @@
 export type HyprctlWorkspace = {
-    id: number,
-    name: string,
-    monitor: string,
-    monitorID: number,
-    windows: number,
-    hasFullscreen: boolean,
-    lastwindows: string,
-    lastwindowtitle: string
-};
-
-export type WorkspaceRule = {
-    workspaceString: string;
-    monitor: string;
+    id: number;
+    monitorID: string;
 };
 ```
</details>

**Comment by Jas-SinghFSU** [comment]
This issue I'm noticing is that this prevents the ability to define minimum workspaces to always show, whether this option is enabled or disabled. This would be a regression in the functionality as always displaying N number of workspaces is a frequently used feature.

**Comment by davfsa** [comment]
Would you mind sharing reproducibility steps @Jas-SinghFSU , because I cannot seem to have it happen on my machine (if you can get a screen recording, that would be insanely helpful too!)

When I disable per monitor bound workspaces, the minimum number of workspaces configuration option is respected

**Comment by Jas-SinghFSU** [comment]
@davfsa Yep, np. I'll provide my config here.
[hyprpanel_config.json](https://github.com/user-attachments/files/18259423/hyprpanel_config_5.json)

**Comment by davfsa** [comment]
@Jas-SinghFSU Just gave your configuration a shot and I am a bit confused on what the behaviour you would like is:

Before patch (hyprpanel installed with yay right before doing the recording)

https://github.com/user-attachments/assets/a1ce5203-b0e3-4ac3-8549-058b20a72e4e

With patch

https://github.com/user-attachments/assets/4cb33a32-581f-45f9-929e-595fa7748b40

It works kind of how I expect. If you would like `Total Workspaces` to be per monitor when `Monitor Specific` is active, then that would require a bit more work, as it doesn't seem to work on the current master either, and should be treated as a separate bug IMO

---

Bit of a sidenote, but since this pr edits it, I might as well also comment on it, "Mask Workspace Numbers On Monitors" is a really confusing naming, as it just kind of makes them sequential, but not in the correct way you expect (as can be seen with workspaces 19 and 20 in the videos). Better naming for the option ("Workspace per monitor" clearly isn't IMO) would be greatly beneficial and fixing that "quirk" (at least I hope it is) could be a follow up PR.

I can create an issue for this and have a look at it myself in the coming days if it is indeed a bug :)

**Comment by Jas-SinghFSU** [comment]
#681 introduces a fix for monitor specific workspaces while also enable the option to use static workspaces. Removing the ability to have static workspaces always visible in the bar would have been a regression so that PR remedies that by doing a combined approach of checking active workspaces and defined workspace rules to determine what to render.

**Pull request closed without merging**
