### PR TITLE
Flake.nix: gnome-bluetooth at top-level

### PR DESCRIPTION
**Pull request by anotherhadi**
Solve the nix warning when building:
trace: evaluation warning: The ‘gnome.gnome-bluetooth’ was moved to top-level. Please use ‘pkgs.gnome-bluetooth’ directly.

### CODE REVIEW

**Comment by painerp** [comment]
I think the warning might be due to using the unstable version of nixpkgs. I'd recommend waiting for the stable 24.10 release before merging this.

**Comment by anotherhadi** [comment]
> I think the warning might be due to using the unstable version of nixpkgs. I'd recommend waiting for the stable 24.10 release before merging this.

Make sense

**Comment by Jas-SinghFSU** [comment]
@anotherhadi @painerp Do we think this is still relevant or should we close this PR?

**Comment by anotherhadi** [comment]
> @anotherhadi @painerp Do we think this is still relevant or should we close this PR?

Still relevant!

**Comment by orxngc** [comment]
> I think the warning might be due to using the unstable version of nixpkgs. I'd recommend waiting for the stable 24.10 release before merging this.

i don't see how this matters



> Do we think this is still relevant or should we close this PR?

yes

**Pull request merged**
