### PR TITLE
feat: osd transitions

### PR DESCRIPTION
**Pull request by rubiin**

### CODE REVIEW

**Comment by Jas-SinghFSU** [comment]
I'm not seeing the transitions take effect for some reason :thinking:

**Comment by rubiin** [comment]
> I'm not seeing the transitions take effect for some reason 🤔

Yeah. Just checked even before the PR , if i change the transition to slide_up, I couldnt see any change. Was there an issue?

**Comment by rubiin** [comment]
@Jas-SinghFSU if you have time can you look into why animations are not working with osd. The osd has crossfade now but that doesnt seem to do anything. I even changed to slide_up to get this kind of effect but no luck. Ignore this pr for now

https://github.com/System64fumo/syshud/blob/main/preview.gif

**Comment by Jas-SinghFSU** [comment]
It's because we're toggling the window on and off, which interrupts the transitions. We have to do this because otherwise, the OSD will occupy the screen space when not visible (reavealed: false) and you can't interact with the window under the invisible OSD. Just some funk we have to deal with unfortunately.

**Comment by rubiin** [comment]
I think I will close it then

**Comment by rubiin** [comment]
@Jas-SinghFSU maybe we can pick some stuffs from here to mimic the implementation

**Pull request closed without merging**
