### PR TITLE
Upgrade to Agsv2 + Astal

### PR DESCRIPTION
**Pull request by Jas-SinghFSU**
# Migration Process
## :tada: Astal/AGSv2 migration is complete.
**:hammer: The branch is under final testing**

### Engine
- [x] CLI Engine

### Commands
- [x] useTheme
- [x] clearAllNotifications
- [x] setWallpaper
- [x] isWindowVisible
- [x] setLayout
- [x] getSystrayItems

## Internal

- [x] Structure
- [x] Options
- [x] Hot Reloading

## Bar Modules

- [x] battery
- [x] dashboard
- [x] workspaces
- [x] windowtitle
- [x] media
- [x] notifications
- [x] volume
- [x] network
- [x] bluetooth
- [x] clock
- [x] systray
- [x] ram
- [x] cpu
- [x] cputemp
- [x] storage
- [x] netstat
- [x] kbinput
- [x] updates
- [x] submap
- [x] weather
- [x] power
- [x] hyprsunset
- [x] hypridle

## Menus

- [x] Dashboard Menu
- [x] Audio Menu
- [x] Media Menu
- [x] Network Menu
- [x] Bluetooth Menu
- [x] Notifications Menu
- [x] Calendar Menu
- [x] Battery Menu
- [x] Power Actions Menu
- [x] **Settings Dialog (In Progress)**

## OSD

- [x] OSD

## Notifications

- [x] Notifications

## Matugen

- [x] Matugen

### CODE REVIEW

**Comment by Beafowl-Pull** [comment]
I'm hyped about this PR, i hope it's going to be merged soon

**Comment by Jas-SinghFSU** [comment]
Should be in within the next couple of days.

**Comment by Beafowl-Pull** [comment]
i try to install the branch to see the modifications but i don't know how to use it so i'm feeling dumb

**Comment by Jas-SinghFSU** [comment]
The migration is pretty much complete. If anyone would like to use this branch you can:
1. Install astal: https://aylur.github.io/astal/guide/getting-started/installation
2. Update your ags
3. From your `~/.config/ags` directory, run `git fetch && git checkout astal`
4. Run the panel via `ags run`

In the meantime, I will be working on bundling the project.

**Comment by Beafowl-Pull** [comment]
> The migration is pretty much complete. If anyone would like to use this branch you can:
> 
> 1. Install astal: https://aylur.github.io/astal/guide/getting-started/installation
> 
> 2. Update your ags  - `yay -Syu aylurs-gtk-shell-git`
> 
> 3. From your `~/.config/ags` directory, run `git fetch && git checkout astal`
> 
> 4. Run the panel via `ags run`
> 
> 
> 
> In the meantime, I will be working on bundling the project.

Do we need to report bugs here if we find some ?

**Comment by Jas-SinghFSU** [comment]
As a separate ticket because I'm going to push this out soon.

**Comment by smathles** [comment]
Ngl I reckon there's going to have to be a big issues/bugs audit after this is pushed lol. I'm expected a lot of existing bugs will need to be binned as "solved in astal" or "doesn't exist anymore" or stale.

image
:eyes: 

I'm most hyped for being able to click a widget twice without having to move the mouse again :tada:

**Comment by smathles** [comment]
yooooooo

**Pull request merged**
