### PR TITLE
Added a Nix Flake and support for running from the Nix Store

### PR DESCRIPTION
**Pull request by mitsuruu**
Addresses comments from #25 (specifically https://github.com/Jas-SinghFSU/HyprPanel/issues/25#issuecomment-2254624002), while allowing for the config to be managed by tools such as Home-Manager.

### CODE REVIEW

**Comment by Jas-SinghFSU** [comment]
Looks good. I will review a bit more once I have some time this weekend and merge. Thanks for contributing, this is great work! :heart:

**Comment by Jas-SinghFSU** [comment]
@mitsuruu When you get a chance could you please merge branch `remove_variable_imports_47 ` into your PR?

It removes the redundant imports atop the scss files which would cause environments to break since these files have been moved to the tmp directory.

**Comment by mitsuruu** [comment]
@Jas-SinghFSU should be good now!

I've verified that it still works when merged and everything seems good.

**Comment by Jas-SinghFSU** [comment]
Perfect, thank you!

**Comment by Jas-SinghFSU** [comment]
I'll get this merged here shortly.

**Pull request merged**
