### PR TITLE
add official arch linux repo updatecheck to script for updates customModules

### PR DESCRIPTION
**Pull request by TheyCallMeSecond**
the current checkUpdates.sh script just check AUR repo for update
i added official repo checkupdates to it

### CODE REVIEW

**Comment by Jas-SinghFSU** [comment]
Could we make this a flag or a different command? :smile: 

Some users may only want to track pacman, aur, or both and I think it would be neat to be able to switch between the choices.

**Comment by TheyCallMeSecond** [comment]
> Could we make this a flag or a different command? 😄
> 
> Some users may only want to track pacman, aur, or both and I think it would be neat to be able to switch between the choices.

separated now with flags

**Review by Jas-SinghFSU — CHANGES_REQUESTED** [review]
Also, do we need to document that `pacman-contrib` needs to be installed to use checkupdates?

**Comment by TheyCallMeSecond** [comment]
> Also, do we need to document that `pacman-contrib` needs to be installed to use checkupdates?

yes

**Review by Jas-SinghFSU — APPROVED** [review]

**Pull request merged**
