### PR TITLE
nix: update flake.lock

### PR DESCRIPTION
**Pull request by emsquid**

### CODE REVIEW

**Comment by emsquid** [comment]
Actually maybe wait to merge that I'm not sure if it's working well...

**Comment by benvonh** [comment]
I think you have to merge because it doesn't build without a flake update after the latest commit https://github.com/Jas-SinghFSU/HyprPanel/commit/a7b553725c1deb4a856ddd8582fa217451533ec3

**Comment by emsquid** [comment]
Same here this is what I get
```zsh
-> hyprpanel
(gjs:8047): GLib-GObject-CRITICAL **: 16:06:36.996: cannot register existing type 'GdkDisplayManager'

(gjs:8047): GLib-CRITICAL **: 16:06:36.996: g_once_init_leave_pointer: assertion 'result != 0' failed

(gjs:8047): GLib-GObject-CRITICAL **: 16:06:36.996: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
zsh: segmentation fault (core dumped)  hyprpanel
```
Maybe I should open an issue

**Comment by lakrestofer** [comment]
> Same here this is what I get
> 
> ```shell
> -> hyprpanel
> (gjs:8047): GLib-GObject-CRITICAL **: 16:06:36.996: cannot register existing type 'GdkDisplayManager'
> 
> (gjs:8047): GLib-CRITICAL **: 16:06:36.996: g_once_init_leave_pointer: assertion 'result != 0' failed
> 
> (gjs:8047): GLib-GObject-CRITICAL **: 16:06:36.996: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
> zsh: segmentation fault (core dumped)  hyprpanel
> ```
> 
> Maybe we should open an issue

I have the same problem with vanilla astal + ags with that exact output. The issue might be upstream? 
https://github.com/Aylur/astal/issues/217

**Comment by Jas-SinghFSU** [comment]
It seems that the nix config is causing segfaults in high frequency but everything else is fine. I'm not sure if it is truly upstream or something wrong on our end

**Comment by benvonh** [comment]
@Jas-SinghFSU fwiw, I got this strack trace. Any help?

```sh
Thread 1 ".hyprpanel-wrap" received signal SIGSEGV, Segmentation fault.
0x00007fffe112a010 in gdk_display_manager_get_default_display () from /nix/store/0whdwl2a2jcykffs7p60h32khzlp2ksd-gtk+3-3.24.43/lib/libgdk-3.so.0
(gdb) bt
#0  0x00007fffe112a010 in gdk_display_manager_get_default_display () from /nix/store/0whdwl2a2jcykffs7p60h32khzlp2ksd-gtk+3-3.24.43/lib/libgdk-3.so.0
#1  0x00007fffe111fc83 in gdk_display_open_default () from /nix/store/0whdwl2a2jcykffs7p60h32khzlp2ksd-gtk+3-3.24.43/lib/libgdk-3.so.0
#2  0x00007fffe141d472 in gtk_init_check () from /nix/store/0whdwl2a2jcykffs7p60h32khzlp2ksd-gtk+3-3.24.43/lib/libgtk-3.so.0
#3  0x00007fffe141d4a9 in gtk_init () from /nix/store/0whdwl2a2jcykffs7p60h32khzlp2ksd-gtk+3-3.24.43/lib/libgtk-3.so.0
#4  0x00007ffff7c35052 in ffi_call_unix64 () from /nix/store/r04wysx6yl7ys1rdv1b1lih6in1810r0-libffi-3.4.6/lib/libffi.so.8
#5  0x00007ffff7c33444 in ffi_call_int () from /nix/store/r04wysx6yl7ys1rdv1b1lih6in1810r0-libffi-3.4.6/lib/libffi.so.8
#6  0x00007ffff7c34280 in ffi_call () from /nix/store/r04wysx6yl7ys1rdv1b1lih6in1810r0-libffi-3.4.6/lib/libffi.so.8
#7  0x00007ffff7e9d2c7 in Gjs::Function::invoke(JSContext*, JS::CallArgs const&, JS::Handle<JSObject*>, _GIArgument*) [clone .localalias] ()
   from /nix/store/sh0w8bsgy51d9299qns5ibylk3fvs1kb-gjs-1.82.1/lib/libgjs.so.0
#8  0x00007ffff7e9d89a in Gjs::Function::call(JSContext*, unsigned int, JS::Value*) () from /nix/store/sh0w8bsgy51d9299qns5ibylk3fvs1kb-gjs-1.82.1/lib/libgjs.so.0
#9  0x00007ffff575459f in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct, js::CallReason) ()
   from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#10 0x00007ffff57460f0 in js::Interpret(JSContext*, js::RunState&) () from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#11 0x00007ffff57542a3 in js::RunScript(JSContext*, js::RunState&) () from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#12 0x00007ffff5754870 in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct, js::CallReason) ()
   from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#13 0x00007ffff5754ae9 in js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>, js::CallReason) ()
   from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#14 0x00007ffff5944a4c in js::CallSelfHostedFunction(JSContext*, JS::Handle<js::PropertyName*>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>) ()
   from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#15 0x00007ffff57cc2ed in AsyncFunctionResume(JSContext*, JS::Handle<js::AsyncFunctionGeneratorObject*>, ResumeKind, JS::Handle<JS::Value>) ()
   from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#16 0x00007ffff58feb55 in PromiseReactionJob(JSContext*, unsigned int, JS::Value*) () from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#17 0x00007ffff575475a in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct, js::CallReason) ()
   from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#18 0x00007ffff5754ae9 in js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>, js::CallReason) ()
   from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#19 0x00007ffff580a633 in JS::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, JS::HandleValueArray const&, JS::MutableHandle<JS::Value>) ()
   from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#20 0x00007ffff7ed664a in GjsContextPrivate::run_jobs_fallible() [clone .part.0] () from /nix/store/sh0w8bsgy51d9299qns5ibylk3fvs1kb-gjs-1.82.1/lib/libgjs.so.0
#21 0x00007ffff7ed6986 in GjsContextPrivate::runJobs(JSContext*) [clone .localalias] () from /nix/store/sh0w8bsgy51d9299qns5ibylk3fvs1kb-gjs-1.82.1/lib/libgjs.so.0
#22 0x00007ffff585f6d4 in js::RunJobs(JSContext*) () from /nix/store/mhl54v3bfsji9iis9fhnnsqc80fpvgz5-spidermonkey-128.5.0/lib/libmozjs-128.so
#23 0x00007ffff7ef194c in Gjs::PromiseJobDispatcher::Source::{lambda(_GSource*, int (*)(void*), void*)#1}::_FUN(_GSource*, int (*)(void*), void*) ()
   from /nix/store/sh0w8bsgy51d9299qns5ibylk3fvs1kb-gjs-1.82.1/lib/libgjs.so.0
#24 0x00007ffff7d52e21 in g_main_context_dispatch_unlocked () from /nix/store/rb870mk51kxlxq9crkldzs8n4vwr9sk4-glib-2.82.1/lib/libglib-2.0.so.0
#25 0x00007ffff7d550e0 in g_main_context_iterate_unlocked.isra () from /nix/store/rb870mk51kxlxq9crkldzs8n4vwr9sk4-glib-2.82.1/lib/libglib-2.0.so.0
#26 0x00007ffff7d5591c in g_main_context_iteration () from /nix/store/rb870mk51kxlxq9crkldzs8n4vwr9sk4-glib-2.82.1/lib/libglib-2.0.so.0
#27 0x00007ffff7ee89ec in Gjs::MainLoop::spin(GjsContextPrivate*) () from /nix/store/sh0w8bsgy51d9299qns5ibylk3fvs1kb-gjs-1.82.1/lib/libgjs.so.0
#28 0x00007ffff7ed9502 in GjsContextPrivate::eval_module(char const*, unsigned char*, _GError**) [clone .localalias] () from /nix/store/sh0w8bsgy51d9299qns5ibylk3fvs1kb-gjs-1.82.1/lib/libgjs.so.0
#29 0x00007ffff7ed964e in gjs_context_eval_module () from /nix/store/sh0w8bsgy51d9299qns5ibylk3fvs1kb-gjs-1.82.1/lib/libgjs.so.0
#30 0x0000000000403373 in define_argv_and_eval_script(_GjsContext*, int, char* const*, char const*, unsigned long, char const*) ()
#31 0x0000000000402b43 in main (
```

**Comment by Jas-SinghFSU** [comment]
> I have the same problem with vanilla astal + ags with that exact output. The issue might be upstream?
https://github.com/Aylur/astal/issues/217

Yea reading that again, it may be the case.

**Pull request closed without merging**
